In [469]:
import pandas as pd
import numpy as np

## CSV Dataset load kora

In [470]:
df = pd.read_csv("students.csv")

df # puro dataset show kore

,StudentID,Name,Age,Email,Department,GPA,GraduationYear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027
3,6716,Kenneth Morrow,24,ganderson@wheeler-atkins.info,Physics,3.55,2029
4,8830,Kaitlyn Martinez,18,hayesdiane@gmail.com,Chemistry,2.29,2025
...,...,...,...,...,...,...,...
195,3274,Catherine Velasquez,22,fsutton@gmail.com,Physics,2.71,2025
196,3609,Joyce Thomas,19,zanderson@barrera.net,Chemistry,2.22,2030
197,9179,Theresa Hughes,21,mstanley@yahoo.com,Mathematics,3.23,2025
198,4463,Steven Golden,19,nvasquez@yahoo.com,Computer Science,3.90,2025
199,6178,Miss April Smith,20,logansanchez@manning.com,Mathematics,3.15,2028

## DataFrame & Series bujha

In [471]:
df.head(3)  # first er 3 ta row dekhabe

,StudentID,Name,Age,Email,Department,GPA,GraduationYear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027

In [472]:
df.tail(2) # last er 2 ta row dekhabe

,StudentID,Name,Age,Email,Department,GPA,GraduationYear
198,4463,Steven Golden,19,nvasquez@yahoo.com,Computer Science,3.90,2025
199,6178,Miss April Smith,20,logansanchez@manning.com,Mathematics,3.15,2028

In [ ]:
# df.sample(5) ---> ata github er junno comment kore dilam       # randomly 5 ta row dekhabe

In [474]:
series = df['Department']
print(series)
print(type(series))
print(type(df))

0           Mathematics
1             Chemistry
2               Physics
3               Physics
4             Chemistry
             ...
195             Physics
196           Chemistry
197         Mathematics
198    Computer Science
199         Mathematics
Name: Department, Length: 200, dtype: str
<class 'pandas.Series'>
<class 'pandas.DataFrame'>

## Basic functionalities

In [475]:
df.shape  # data set er shape dekha jai

(200, 7)

In [476]:
df.columns   # dataset er features column dekha jai

Index(['StudentID', 'Name', 'Age', 'Email', 'Department', 'GPA',
       'GraduationYear'],
      dtype='str')

In [477]:
df.index   # dataset er index dekhar junno

RangeIndex(start=0, stop=200, step=1)

In [478]:
df.dtypes  # dataset ea datar type dekhar junno

StudentID           int64
Name                  str
Age                 int64
Email                 str
Department            str
GPA               float64
GraduationYear      int64
dtype: object

In [479]:
df.info()  # dataset er summary dekhar junno

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   StudentID       200 non-null    int64
 1   Name            200 non-null    str
 2   Age             200 non-null    int64
 3   Email           200 non-null    str
 4   Department      200 non-null    str
 5   GPA             200 non-null    float64
 6   GraduationYear  200 non-null    int64
dtypes: float64(1), int64(3), str(3)
memory usage: 11.1 KB

In [ ]:
df.describe()   # Numeric column er statistics dekhar junno

         StudentID         Age        GPA  GraduationYear
count   200.000000  200.000000  200.00000      200.000000
mean   5726.460000   21.580000    3.02785     2027.180000
std    2507.407622    2.267002    0.59112        2.011924
min    1066.000000   18.000000    2.00000     2024.000000
25%    3693.000000   20.000000    2.52500     2025.000000
50%    5641.000000   22.000000    3.08000     2027.000000
75%    8025.750000   24.000000    3.51000     2029.000000
max    9985.000000   25.000000    3.99000     2030.000000

In [481]:
df.isnull().sum()   # Missing value er sonkha dekhar junno

StudentID         0
Name              0
Age               0
Email             0
Department        0
GPA               0
GraduationYear    0
dtype: int64

In [482]:
df.duplicated().sum()   # Duplicate row sonkha dekhar junno

np.int64(0)

 ## Built-in date diye  DataFrame create

In [483]:
dates = pd.date_range(start="2026-10-01", periods=10, freq="D")

data = {
    "Student": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    "Marks": [85, 72, 90, 65, 78, 88, 95, 60, 82, 74],
    "Attendance": [92, 85, 98, 70, 88, 95, 100, 65, 90, 80]
}

date_df = pd.DataFrame(data, index=dates)
date_df.index.name = "Date"

date_df

           Student  Marks  Attendance
Date
2026-10-01       A     85          92
2026-10-02       B     72          85
2026-10-03       C     90          98
2026-10-04       D     65          70
2026-10-05       E     78          88
2026-10-06       F     88          95
2026-10-07       G     95         100
2026-10-08       H     60          65
2026-10-09       I     82          90
2026-10-10       J     74          80

Custom column 0 custom index sho DataFrame:

In [484]:
custom_df = pd.DataFrame(
    [[85, 21], [90, 22], [78, 20]],
    columns=["Marks", "Age"],
    index=["S1", "S2", "S3"]
)

custom_df

    Marks  Age
S1     85   21
S2     90   22
S3     78   20

## Index o column diye data access

In [485]:
df.head(2)

,StudentID,Name,Age,Email,Department,GPA,GraduationYear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027

In [486]:
df['GPA']   # akti GPA column dekhar junno

0      3.16
1      3.75
2      2.95
3      3.55
4      2.29
       ...
195    2.71
196    2.22
197    3.23
198    3.90
199    3.15
Name: GPA, Length: 200, dtype: float64

In [487]:
df[['Name', 'Age']]   # multiple column dekhar junno

                    Name  Age
0           David Palmer   19
1           Andrew Roach   23
2      Jonathan Gonzalez   22
3         Kenneth Morrow   24
4       Kaitlyn Martinez   18
..                   ...  ...
195  Catherine Velasquez   22
196         Joyce Thomas   19
197       Theresa Hughes   21
198        Steven Golden   19
199     Miss April Smith   20

[200 rows x 2 columns]

In [488]:
df[['Age', 'Name' ]]   # Column- er order change kore select

     Age                 Name
0     19         David Palmer
1     23         Andrew Roach
2     22    Jonathan Gonzalez
3     24       Kenneth Morrow
4     18     Kaitlyn Martinez
..   ...                  ...
195   22  Catherine Velasquez
196   19         Joyce Thomas
197   21       Theresa Hughes
198   19        Steven Golden
199   20     Miss April Smith

[200 rows x 2 columns]

.iloc — position diyea access

In [489]:
df.iloc[0]  # first row dekhabe

StudentID                       3336
Name                    David Palmer
Age                               19
Email             sean43@hotmail.com
Department               Mathematics
GPA                             3.16
GraduationYear                  2026
Name: 0, dtype: object

In [490]:
df.iloc[-1]   # last row dekhabe

StudentID                             6178
Name                      Miss April Smith
Age                                     20
Email             logansanchez@manning.com
Department                     Mathematics
GPA                                   3.15
GraduationYear                        2028
Name: 199, dtype: object

In [491]:
df.iloc[0,1]  # Row position 0 and column position 1 er value dekhabe

'David Palmer'

In [492]:
df.iloc[0:3]  # first 3 row dekhabe

,StudentID,Name,Age,Email,Department,GPA,GraduationYear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027

In [493]:
df.iloc[0:3, 0:2]    # first 3ta row o 2ta column er value dekhabe

   StudentID               Name
0       3336       David Palmer
1       8774       Andrew Roach
2       1396  Jonathan Gonzalez

In [494]:
df.iloc[[0, 2, 4, 9]]  # Specific position er value dekhbe

,StudentID,Name,Age,Email,Department,GPA,GraduationYear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027
4,8830,Kaitlyn Martinez,18,hayesdiane@gmail.com,Chemistry,2.29,2025
9,6622,Emily Davis,18,george02@hotmail.com,Physics,3.09,2030

In [495]:
df.iloc[[0, 2, 4, 9], [0, 1, 4]]   # Specific row o column positions er element dekhabe

   StudentID               Name   Department
0       3336       David Palmer  Mathematics
2       1396  Jonathan Gonzalez      Physics
4       8830   Kaitlyn Martinez    Chemistry
9       6622        Emily Davis      Physics

## Index o columns change kora

In [496]:
set_indx = df.set_index("StudentID")  # column ke index kore

set_indx.head(3)

,Name,Age,Email,Department,GPA,GraduationYear
StudentID,,,,,,
3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027

In [497]:
res_indx = set_indx.reset_index()  # column index ke reset

res_indx.head(3)

,StudentID,Name,Age,Email,Department,GPA,GraduationYear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027

In [498]:
col_rename = df.rename(columns={'StudentID' : 'Student ID'})  # single column er name rename kore
col_rename.head(2)

,Student ID,Name,Age,Email,Department,GPA,GraduationYear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027

In [499]:
# multiple column er name rename kore 

col_re = df.rename(columns = {
    'Name' : 'name',
    'Age' : 'age',
    'Email' : 'email'
})

col_re.head(2)

,StudentID,name,age,email,Department,GPA,GraduationYear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027

In [500]:
df.columns = [col.upper() for col in df.columns]   # all columns name upper case ea convert kore
df.head(2)

,STUDENTID,NAME,AGE,EMAIL,DEPARTMENT,GPA,GRADUATIONYEAR
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027

In [501]:
df.columns = [col.lower() for col in df.columns]   # all columns ke lower case ea convert kore
df.head(2)

,studentid,name,age,email,department,gpa,graduationyear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027

## Row & column drop kora

In [502]:
drop_col = df.drop(columns= ['studentid'])  # akhane studentid column drop kora hoise

drop_col.head(3)

,name,age,email,department,gpa,graduationyear
0,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
2,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027

In [503]:
drop_col = df.drop(columns= ['age', 'email', 'department'])  # multiple column drop kora hocce

drop_col.head(2)

   studentid          name   gpa  graduationyear
0       3336  David Palmer  3.16            2026
1       8774  Andrew Roach  3.75            2027

Index use kore row drop kora

In [504]:
drop_row = df.drop(index= 0)  # single row drop korce

drop_row.head(3)

,studentid,name,age,email,department,gpa,graduationyear
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027
3,6716,Kenneth Morrow,24,ganderson@wheeler-atkins.info,Physics,3.55,2029

In [505]:
drop_row = df.drop(index= [1, 3, 5])  # Specific multiple row drop korce

drop_row.head(5)

,studentid,name,age,email,department,gpa,graduationyear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027
4,8830,Kaitlyn Martinez,18,hayesdiane@gmail.com,Chemistry,2.29,2025
6,5048,James Reyes,20,drodriguez@nguyen-cooper.info,Chemistry,2.44,2029
7,5986,Samantha Sellers,20,michelle27@hubbard-webster.com,Mathematics,3.44,2025

## Value assign kora

In [506]:
copy_df = df.copy() # dataframe er copy kora hoyese
copy_df['gpa'] = 'A'  # puro column ea value assin kore
copy_df.head(4)

,studentid,name,age,email,department,gpa,graduationyear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,A,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,A,2027
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,A,2027
3,6716,Kenneth Morrow,24,ganderson@wheeler-atkins.info,Physics,A,2029

In [ ]:
copy_df["age"] = np.where(df["age"] >= 20, "Adult", "Young")  # condition anujai value assing

copy_df.sample(5)

,studentid,name,age,email,department,gpa,graduationyear
196,3609,Joyce Thomas,Young,zanderson@barrera.net,Chemistry,A,2030
79,5652,Brooke Davis,Young,millerkevin@white.com,Chemistry,A,2030
172,5149,Mallory May,Adult,morrisonlucas@gmail.com,Biology,A,2029
199,6178,Miss April Smith,Adult,logansanchez@manning.com,Mathematics,A,2028
109,1666,Jaime Hanson,Adult,whitechristine@gonzalez.info,Computer Science,A,2027

In [ ]:
copy_df.loc[0, 'name'] = 'Mehedi'  # akhane row er specific value change kora hoyse --label diye
 
copy_df.head(3)

,studentid,name,age,email,department,gpa,graduationyear
0,3336,Mehedi,Young,sean43@hotmail.com,Mathematics,A,2026
1,8774,Andrew Roach,Adult,vbecker@harvey.com,Chemistry,A,2027
2,1396,Jonathan Gonzalez,Adult,hollydavis@gmail.com,Physics,A,2027

Specific cell ea value change — position diyea

In [515]:
copy_df.iloc[1, copy_df.columns.get_loc("department")] = 'CST'

copy_df.head(3)

,studentid,name,age,email,department,gpa,graduationyear
0,3336,Mehedi,Young,sean43@hotmail.com,Mathematics,A,2026
1,8774,Andrew Roach,Adult,vbecker@harvey.com,CST,A,2027
2,1396,Jonathan Gonzalez,Adult,hollydavis@gmail.com,Physics,A,2027

In [521]:
copy2_df = df.copy()
copy2_df['age'] = copy2_df['age'] + 10   # akhane age column er age er sathe 10 add korbe

copy2_df.head(4)

,studentid,name,age,email,department,gpa,graduationyear
0,3336,David Palmer,29,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,33,vbecker@harvey.com,Chemistry,3.75,2027
2,1396,Jonathan Gonzalez,32,hollydavis@gmail.com,Physics,2.95,2027
3,6716,Kenneth Morrow,34,ganderson@wheeler-atkins.info,Physics,3.55,2029

In [ ]:
copy2_df["result"] = np.where(copy2_df["gpa"] >= 3, "Pass", "Fail")   # new column add kora

copy2_df.head(4)

,studentid,name,age,email,department,gpa,graduationyear,result
0,3336,David Palmer,29,sean43@hotmail.com,Mathematics,3.16,2026,Pass
1,8774,Andrew Roach,33,vbecker@harvey.com,Chemistry,3.75,2027,Pass
2,1396,Jonathan Gonzalez,32,hollydavis@gmail.com,Physics,2.95,2027,Fail
3,6716,Kenneth Morrow,34,ganderson@wheeler-atkins.info,Physics,3.55,2029,Pass

 ## DataFrame sorting

In [533]:
asen_sort = df.sort_values('age')    # ascending short

asen_sort.head(3)

,studentid,name,age,email,department,gpa,graduationyear
4,8830,Kaitlyn Martinez,18,hayesdiane@gmail.com,Chemistry,2.29,2025
9,6622,Emily Davis,18,george02@hotmail.com,Physics,3.09,2030
20,3052,Suzanne Lopez,18,thomasbennett@gmail.com,Computer Science,2.33,2025

In [532]:
des_sort = df.sort_values('age', ascending=False)   # Descending sort

des_sort.head(3)

,studentid,name,age,email,department,gpa,graduationyear
47,3719,Melanie Lowe,25,nicolepruitt@bell-gibson.org,Computer Science,3.05,2030
48,9310,Isaiah Morales,25,lutzjason@neal.biz,Physics,3.06,2025
54,8431,Julie Martin,25,angelawilliams@gmail.com,Chemistry,3.56,2030

In [ ]:
df_sorted = df.sort_values(["age", "gpa"], ascending=[False, True])  # multiple columns sort

df_sorted.head(5)

,studentid,name,age,email,department,gpa,graduationyear
173,9098,Larry Torres,25,rachel70@hotmail.com,Physics,2.01,2030
192,3406,Jonathan Blanchard,25,jonathanfoster@sanchez.com,Computer Science,2.06,2026
174,2991,Tina Mccormick,25,zthompson@lee.com,Physics,2.09,2027
59,4514,Arthur Thornton,25,kirstenowen@yahoo.com,Biology,2.10,2024
87,4418,Rachel Mahoney MD,25,teresamitchell@hernandez.net,Computer Science,2.14,2028

In [539]:
df_sorted = df.sort_index(axis=1)  # columns name anujai sort

df_sorted.head(3)

,age,department,email,gpa,graduationyear,name,studentid
0,19,Mathematics,sean43@hotmail.com,3.16,2026,David Palmer,3336
1,23,Chemistry,vbecker@harvey.com,3.75,2027,Andrew Roach,8774
2,22,Physics,hollydavis@gmail.com,2.95,2027,Jonathan Gonzalez,1396

## Condition use kore filtering

In [542]:
gpa = df[df["gpa"] > 3]   # gpa 3 er ceye beshi segulo show korbe

gpa.head(4)

,studentid,name,age,email,department,gpa,graduationyear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
3,6716,Kenneth Morrow,24,ganderson@wheeler-atkins.info,Physics,3.55,2029
5,5305,Tiffany Wolf,23,qanderson@taylor.com,Mathematics,3.30,2029

In [ ]:
gpa2 = df[(df["gpa"] > 3) & (df["gpa"] > 2.5)]   # multiple condition 'AND' use

gpa2.head(4)

,studentid,name,age,email,department,gpa,graduationyear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
3,6716,Kenneth Morrow,24,ganderson@wheeler-atkins.info,Physics,3.55,2029
5,5305,Tiffany Wolf,23,qanderson@taylor.com,Mathematics,3.30,2029

In [550]:
age = df[(df["age"] > 33) | (df["age"] > 20)]   # multiple condition 'OR' use kore

age.head(5)

,studentid,name,age,email,department,gpa,graduationyear
1,8774,Andrew Roach,23,vbecker@harvey.com,Chemistry,3.75,2027
2,1396,Jonathan Gonzalez,22,hollydavis@gmail.com,Physics,2.95,2027
3,6716,Kenneth Morrow,24,ganderson@wheeler-atkins.info,Physics,3.55,2029
5,5305,Tiffany Wolf,23,qanderson@taylor.com,Mathematics,3.30,2029
8,8721,Michael Kim,25,jacksonhannah@miles.com,Computer Science,3.27,2027

In [ ]:
age2 = df[~(df["age"] > 19)]   # NOT condition use kor

age2.head(5)

,studentid,name,age,email,department,gpa,graduationyear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026
4,8830,Kaitlyn Martinez,18,hayesdiane@gmail.com,Chemistry,2.29,2025
9,6622,Emily Davis,18,george02@hotmail.com,Physics,3.09,2030
20,3052,Suzanne Lopez,18,thomasbennett@gmail.com,Computer Science,2.33,2025
26,7657,Andrea Castro,19,valvarez@hotmail.com,Mathematics,3.16,2024

In [ ]:
name = df[df["name"].isin(["David Palmer", "Rahim"])]  # Specific values thake row dekhabe

name

,studentid,name,age,email,department,gpa,graduationyear
0,3336,David Palmer,19,sean43@hotmail.com,Mathematics,3.16,2026

.loc diyea Boolean filtering kora jai

In [565]:
gp = df.loc[df["gpa"] > 3.96]

gp

,studentid,name,age,email,department,gpa,graduationyear
85,2921,Sean Davis,24,tina80@miller-navarro.com,Computer Science,3.97,2024
102,7574,Robert Berg,24,stephensbrenda@perez.com,Physics,3.97,2030
142,7265,Kevin Bowman,25,brownronald@clay.com,Chemistry,3.98,2030
152,7637,Peter Day,19,smaynard@cole.com,Mathematics,3.99,2029
170,8314,Clinton Weber,25,bhiggins@jenkins-stevenson.com,Biology,3.98,2027